### ISSUE TITLE
Create a basic abstraction for a logic gate

### ISSUE THREAD

**Issue by rep-movsd** [rep-movsd/9d#3]

**Comment by rep-movsd** [comment]
Start by making a simple NAND abstraction

Will have to revist how to abstract compositions of gates to perform efficiently when 100000s of them are wired up

**Comment by dumptyd** [comment]
Can the whole thing be made in JS too?

**Comment by rep-movsd** [comment]
we will try compileing teh C++ code in emscripten
the UI can be in JS for a web version
